services:
  web:
    image: "${IMAGE}"
    build: false
    volumes: []
    command: gunicorn Online_school.wsgi:application --bind 0.0.0.0:8000 --log-level debug --access-logfile - --error-logfile - --timeout 120 --preload
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DEBUG_MODE: ${DEBUG_MODE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      LANGUAGE_CODE: ${LANGUAGE_CODE}
      PYTHONUNBUFFERED: 1
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1