# Generated by Django 5.2 on 2025-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
