# Generated by Django 5.2 on 2025-05-04 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_start_date_alter_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_on'], 'verbose_name': 'Запись о зачислении студента на сессию', 'verbose_name_plural': 'Записи о зачислении студента на сессию'},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('unready', 'Не выдан'), ('conditionally', 'Условно-освидетельствовано (не все выполнено)'), ('control received', 'Условно-освидетельствовано: поступила контрольная'), ('in_progress', 'Готовится'), ('completed', 'Готов в электронной форме')], default='unready'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_on',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_on',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
