# Generated by Django 5.2 on 2025-05-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_enrollment_options_remove_enrollment_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('unready', 'Не выдан'), ('conditionally', 'Условно-освидетельствовано (не все выполнено)'), ('control_received', 'Условно-освидетельствовано: поступила контрольная'), ('in_progress', 'Готовится'), ('completed', 'Готов в электронной форме')], default='unready', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('planned', 'Зачисляется'), ('in_progress', 'Учится'), ('completed', 'Закончил')], default='planned', max_length=20),
        ),
    ]
