# Generated by Django 5.2 on 2025-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_enrollment_unique_enrollment_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_enrollment'),
        ),
    ]
