# Generated by Django 5.2 on 2025-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enrollment_unique_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес в итоговой оценке (в %)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='sessions_attended',
            field=models.IntegerField(default=0, verbose_name='К-во сессий с момента начала обучения'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='certified',
            field=models.IntegerField(verbose_name='Кол. освидетельствованных предметов'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='sessions_late',
            field=models.IntegerField(default=0, verbose_name='К обуч. приступил с опозданием на (X) сессий'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='sessions_missed',
            field=models.IntegerField(verbose_name='Кол. пропущенных сессий'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_courses',
            field=models.IntegerField(verbose_name='Кол. прослушанных предметов'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='uncertified',
            field=models.IntegerField(verbose_name='Кол. неосвидетельствованных предметов'),
        ),
    ]
