# Generated by Django 5.2 on 2025-05-28 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250524_1409'),
    ]

    operations = [
        # Удаляем старую таблицу сертификатов
        migrations.DeleteModel(
            name='Certificate',
        ),
        
        # Создаем новую таблицу сертификатов
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(default=django.utils.timezone.now, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('type', models.CharField(choices=[('unready', 'Не выдан'), ('conditionally', 'Условно-освидетельствовано (не все выполнено)'), ('control_received', 'Условно-освидетельствовано: поступила контрольная'), ('in_progress', 'Готовится'), ('completed', 'Готов в электронной форме')], default='unready', max_length=20, verbose_name='Статус')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.assessment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.student')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_on'],
            },
        ),
        
        # Обновляем статусы зачисления
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'Учится'), ('completed', 'Закончил')], default='planned', max_length=20),
        ),
        
        # Добавляем русификацию для поля present
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(verbose_name='Присутствовал'),
        ),
    ]
