# Generated by Django 5.2 on 2025-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250529_0051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment',
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_final_grade',
            field=models.BooleanField(default=False, verbose_name='Итоговая оценка за предмет'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='sessions_attended',
            field=models.IntegerField(verbose_name='К-во сессий с момента начала обучения'),
        ),
    ]
