# Generated by Django 5.2 on 2025-05-29 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enrollment_unique_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='certificate_issued',
            field=models.BooleanField(default=False, verbose_name='Сертификат выдан'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.course', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.enrollment', verbose_name='Зачисление'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=100, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.assessmenttype', verbose_name='Тип зачета'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес в итоговой оценке (%)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_on',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.session', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'Учится'), ('completed', 'Закончил')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student', verbose_name='Студент'),
        ),
    ]
